name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Déclenche la pipeline sur un push vers la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Machine virtuelle Ubuntu pour le job

    steps:
    # 1. Checkout du code source
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Mise à jour des paquets et installation de openssh-client
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-client

    # 3. Configuration de la clé SSH privée pour se connecter à EC2
    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    # 4. Ajouter l'hôte SSH à known_hosts pour éviter les erreurs
    - name: Set up SSH known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
        chmod 700 ~/.ssh
        chmod 644 ~/.ssh/known_hosts

    # 5. Déploiement via SSH sur l'instance EC2
    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST << EOF
          cd $WORK_DIR  # Naviguer vers le répertoire du projet
          git pull origin $MAIN_BRANCH  # Récupérer les dernières modifications
        EOF

    # 6. Nettoyage des fichiers sensibles
    - name: Clean up
      run: |
        rm -rf ~/.ssh
