name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier et configurer le dépôt
      - name: Checkout repository
        uses: actions/checkout@v2

      # Étape 2 : Configuration des clés SSH
      - name: Set up SSH keys
        run: |
          # 1. Créer le répertoire ~/.ssh s'il n'existe pas
          mkdir -p ~/.ssh

          # 2. Vérifier et afficher la valeur de SSH_HOST pour débogage
          echo "SSH_HOST: $SSH_HOST"

          # 3. Vérifier si la variable SSH_HOST est définie
          if [ -z "$SSH_HOST" ]; then
            echo "ERROR: SSH_HOST is not set"
            exit 1
          fi

          # 4. Ajouter la clé privée SSH dans ~/.ssh/id_rsa
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa

          # 5. Donner les permissions appropriées à la clé privée
          chmod 600 ~/.ssh/id_rsa

          # 6. Ajouter l'hôte SSH à known_hosts pour éviter les erreurs de vérification
          # Afficher un message pour vérifier si l'hôte est bien ajouté
          echo "Adding SSH host to known_hosts"
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

      # Étape 3 : Déploiement sur EC2 via SSH
      - name: Deploy on EC2
        run: |
          echo "Starting deployment on EC2..."

          # Connexion à l'instance EC2 via SSH et exécution du git pull
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST "cd $WORK_DIR && git pull origin $MAIN_BRANCH"

