name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier la branche 'main'
      - name: Checkout repository
        uses: actions/checkout@v2

      # Étape 2 : Mettre à jour les paquets
      - name: Update packages
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y

      # Étape 3 : Installer openssh-client
      - name: Install openssh-client
        run: |
          sudo apt-get install -y openssh-client

      # Étape 4 : Configurer les clés SSH
      - name: Set up SSH keys
        run: |
          # Créer le répertoire ~/.ssh
          mkdir -p ~/.ssh

          # Ajouter la clé privée SSH à ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

          # Appliquer les bonnes permissions à la clé privée
          chmod 600 ~/.ssh/id_rsa

          # Ajouter l'hôte SSH à known_hosts pour éviter les erreurs de vérification
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # Étape 5 : Déployer sur EC2 via SSH
      - name: Deploy on EC2
        run: |
          # Se connecter à l'instance EC2 et effectuer un git pull pour mettre à jour l'application
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git pull origin main"

      # Étape 6 : Nettoyage du répertoire .ssh
      - name: Clean up SSH keys
        run: |
          # Supprimer le répertoire .ssh pour des raisons de sécurité
          rm -rf ~/.ssh
