name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Vérifier les secrets
      - name: Check secrets
        run: |
          echo "SSH_HOST: ${{ secrets.SSH_HOST }}"
          echo "SSH_USER: ${{ secrets.SSH_USER }}"

      # Installer les paquets nécessaires
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client

      # Créer le répertoire .ssh et configurer les clés SSH
      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          # Ajouter la clé privée SSH à ~/.ssh/id_rsa
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Ajouter l'hôte à known_hosts pour éviter les erreurs de type "host verification"
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
          
      # Test de la clé SSH avec une commande debug
      - name: Test SSH connection
        run: |
          echo "Testing SSH connection..."
          ssh -v -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST "exit"
        
      # Se connecter en SSH et exécuter git pull
      - name: Deploy application via SSH
        run: |
          echo "Deploying application..."
          ssh -v -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST << 'EOF'
            cd /path/to/your/application
            git pull origin main
            # Ajouter d'autres commandes pour déployer, si nécessaire
          EOF

      # Supprimer les fichiers .ssh
      - name: Clean up
        run: |
          rm -rf ~/.ssh
